// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuzisbplsajjuxlfrlqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1emlzYnBsc2FqanV4bGZybHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjk2MjksImV4cCI6MjA2MDYwNTYyOX0.touOecPo7MOelYMAIIZb3_hwhnORmQwIX5C4ECsfMR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);